name: Docker-Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch and if tags are created 
  push:
    branches: [ master ]
    paths: 
      - '**/docker/*'
  pull_request:
    branches: [ master ]
    paths: 
      - '**/docker/*'
  create:
    tags: [docker-v*.*.*]

  workflow_dispatch:
  
jobs:
  docker-build:
    env:
      working-directory: "./docker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    

      - name: login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
          logout: true

      - name: build 
        working-directory: ${{env.working-directory}}
        run: python3 ./build.py   
        
      - name: push
        working-directory: ${{env.working-directory}}
        if: startsWith(github.ref, 'refs/tags/docker-v')
        run: python3 ./build.py --gitref ${{ github.ref }}
      
        
